import Head from "next/head";
import { Inter } from "@next/font/google";

import { useSelector, useDispatch } from "react-redux";
import { decrement, increment, valueSelector } from "../slices/counterSlice";

import TransformationSection from "../components/sections/transformation_section";

import HomeAppBar from "../components/organisms/app_bar";
// import Loading from "../organisms/loading";
import Hero from "../components/organisms/hero";
import CardGrid from "../components/organisms/card_grid";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const counter = useSelector(valueSelector);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="flex flex-col "
        style={{
          background:
            "radial-gradient(circle at -1% 57.5%, #0a231d 0%, #0a231d 90%)",
        }}
      >
        <HomeAppBar />
        <Hero />
        {/* <Loading /> */}

        <TransformationSection />

        <CardGrid />
      </div>
    </>
  );
}
